on:
  push:
    branches: [oven]

name: Windows Build
jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Install msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            msys/autoconf
            mingw64/mingw-w64-x86_64-gcc
            mingw64/mingw-w64-x86_64-protobuf
            mingw64/mingw-w64-x86_64-cmake

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          arch: win64_mingw81

      - name: Checkout Qbs
        uses: actions/checkout@v2
        with:
          repository: qbs/qbs
          path: qbs-build
          submodules: recursive

      - name: Build and install Qbs
        run: |
          cd qbs-build
          qmake -r qbs.pro
          mingw32-make -j10 install
          cd ..

      - name: Setup Qbs toolchains
        shell: msys2 {0}
        run: |
          qbs setup-toolchains --detect

      - name: Build
        shell: msys2 {0}
        run: |
          qbs profile:x86_64-w64-mingw32-gcc-10_2_0 project.vendoredKirigami:true project.vendoredProtobuf:true qbs.buildVariant:'release' -j4
