on:
  push:
    branches: [oven]

name: Windows Build
jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Install msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            msys/autoconf
            mingw64/mingw-w64-x86_64-gcc
            mingw64/mingw-w64-x86_64-protobuf
            mingw64/mingw-w64-x86_64-cmake
            mingw64/mingw-w64-x86_64-qbs
            mingw64/mingw-w64-x86_64-wget

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          arch: win64_mingw81

      - name: Screw with Qbs
        shell: msys2 {0}
        run: |
          wget https://gist.githubusercontent.com/pontaoski/2086ef66f04c728cf6241b39ee77ed04/raw/e576267632f76c0b7b035a5dc9e7d55775ded1ec/eep -o /mingw64/share/qbs/modules/protobuf/cpp/protobufcpp.qbs
          cat /mingw64/share/qbs/modules/protobuf/cpp/protobufcpp.qbs

      - name: Setup Qbs toolchains
        shell: msys2 {0}
        run: |
          qbs setup-toolchains --detect

      - name: Build
        shell: msys2 {0}
        run: |
          qbs profile:x86_64-w64-mingw32-gcc-10_2_0 project.vendoredKirigami:true project.vendoredProtobuf:true qbs.buildVariant:'release' -j4
